project_id = "gqmblotcoddbcylgxcwe"

[functions.cardknox-customer]
verify_jwt = false

[functions.create-account]
verify_jwt = false

[functions.setup-shulowner]
verify_jwt = false

[functions.send-email]
verify_jwt = false